---
# defaults file for prometheus-exporter
prometheus_account: prometheus

# prometheus exporter packages
exporter_packages: https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-amd64.tar.gz
exporter_service: node-exporter
base_dir: node_exporter-1.10.2.linux-amd64
exporter_directory: "/usr/local/prometheus-{{ exporter_service }}"
exporter_port: 9100

mysql_user: prometheus
mysql_pass: centos

# option key
#   - 0 : node exporter
#   - 1 : mysql exporter
#   - 2 : apache exporter
#   - 3 : prometheus server
#   - 4 : reids exporter
option_key: 0

# prometheus server
# targets:
#   - name: node_exporter
#     ip: 192.168.10.30
#     port: 9100
#     app_label: '[node] mariadb.example.com'
#   - name: mysql_exporter
#     ip: "192.168.10.30"
#     port: 9104
#     app_label: '[mysql] mariadb.example.com'
#   - name: mysql_exporter
#     ip: 192.168.10.10
#     port: 9100
#     app_label: '[node] web.example.com'
#   - name: apache_exporter
#     ip: 192.168.10.10
#     port: 9117
#     app_label: '[apache] web.example.com'