---
# tasks file for apache
- name: 'Install packages'
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present

- name: 'Deploy /etc/httpd/conf/httpd.conf'
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: '0644'

- name: 'Create apache status url'
  ansible.builtin.blockinfile:
    path: /etc/httpd/conf.d/status.conf
    block: |
      <Location /server-status>
        SetHandler server-status
        Require ip 127.0.0.1
      </Location>
      ExtendedStatus On
    owner: root
    group: root
    mode: '0644'
    create: true

- name: 'Restart redis'
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true

- name: 'Add service for firewalld'
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - "{{ apache_listen }}/tcp"
